export interface StreetTypeModel {
  type: string;
  abbr: string;
}

export enum StreetType {
  Alley = 'Alley',
  Arcade = 'Arcade',
  Avenue = 'Avenue',
  Boulevard = 'Boulevard',
  Bypass = 'Bypass',
  Circuit = 'Circuit',
  Close = 'Close',
  Corner = 'Corner',
  Court = 'Court',
  Crescent = 'Crescent',
  CulDeSac = 'CulDeSac',
  Drive = 'Drive',
  Esplanade = 'Esplanade',
  Green = 'Green',
  Grove = 'Grove',
  Highway = 'Highway',
  Junction = 'Junction',
  Lane = 'Lane',
  Link = 'Link',
  Mews = 'Mews',
  Parade = 'Parade',
  Place = 'Place',
  Ridge = 'Ridge',
  Road = 'Road',
  Square = 'Square',
  Street = 'Street',
  Terrace = 'Terrace',
}

export const StreetTypes: StreetTypeModel[] = [
  { type: 'Alley', abbr: 'Ally' },
  { type: 'Arcade', abbr: 'Arc' },
  { type: 'Avenue', abbr: 'Ave' },
  { type: 'Boulevard', abbr: 'Bvd' },
  { type: 'Bypass', abbr: 'Bypa' },
  { type: 'Circuit', abbr: 'Cct' },
  { type: 'Close', abbr: 'Cl' },
  { type: 'Corner', abbr: 'Crn' },
  { type: 'Court', abbr: 'Ct' },
  { type: 'Crescent', abbr: 'Cres' },
  { type: 'CulDeSac', abbr: 'Cds' },
  { type: 'Drive', abbr: 'Dr' },
  { type: 'Esplanade', abbr: 'Esp' },
  { type: 'Green', abbr: 'Grn' },
  { type: 'Grove', abbr: 'Gr' },
  { type: 'Highway', abbr: 'Hwy' },
  { type: 'Junction', abbr: 'Jnc' },
  { type: 'Lane', abbr: 'Lane' },
  { type: 'Link', abbr: 'Link' },
  { type: 'Mews', abbr: 'Mews' },
  { type: 'Parade', abbr: 'Pde' },
  { type: 'Place', abbr: 'Pl' },
  { type: 'Ridge', abbr: 'Rdge' },
  { type: 'Road', abbr: 'Rd' },
  { type: 'Square', abbr: 'Sq' },
  { type: 'Street', abbr: 'St' },
  { type: 'Terrace', abbr: 'Tce' },
];
